/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 frontend/public/trophy.glb --types --output frontend/src/components/trophy/TrophyModel.tsx 
*/

import { useGLTF } from '@react-three/drei'

type TrophyNodes = {
  mesh_0: {
    geometry: unknown
    material: unknown
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  // The project resolves two compatible Three type packages. Preserve the
  // gltfjsx-generated geometry and material references structurally instead
  // of tying the generated asset to either package's internal types.
  const { nodes } = useGLTF('/trophy.glb') as unknown as { nodes: TrophyNodes }
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry as never} material={nodes.mesh_0.material as never} />
    </group>
  )
}

useGLTF.preload('/trophy.glb')
